#!/usr/bin/python

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import os
# use chromedriver to driver chrome for selenium
abspath = os.path.abspath(r"C:\Program Files (x86)\Google\Chrome\Application\chromedriver.exe")
dr = webdriver.Chrome(abspath)
# take in the location of game net
#dr.get("file:///C:/Users/Administrator/Desktop/1-50%EF%BC%8C%E7%9C%8B%E8%B0%81%E7%82%B9%E5%BE%97%E5%BF%AB.html")
dr.get("http://wap.jue-huo.com/app/html/game/1to50/1to50.html?from=singlemessage&isappinstalled=0l")
print(dr.title)
#dr.get("http://www.yahoo.com")
#assert 'Yahoo' in dr.title

#elem = dr.find_element_by_name('p')
#elem.send_keys('china' + Keys.RETURN)
# ==== control chrome to change the number sequency
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:99']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:98']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:97']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:96']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:95']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:94']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:93']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:92']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:91']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:90']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:89']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:88']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:87']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:86']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:85']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:84']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:83']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:82']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:81']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:80']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:79']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:78']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:77']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:76']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:75']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:74']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:73']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:72']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:71']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:70']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:69']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:68']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:67']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:66']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:65']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:64']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:63']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:62']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:61']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:60']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:59']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:58']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:57']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:56']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:55']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:54']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:53']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:52']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:51']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:50']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:49']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:48']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:47']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:46']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:45']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:44']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:43']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:42']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:41']").click()
dr.find_element_by_xpath("//*[@id='grid']/div[*]/span[@style='z-index:40']").click()

# ==== simulation to click the num by sequency
#//*[@id="grid"]/div[2]/span

#dr.close()
